# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dae3a73bfc10bfbb7795218ac3ba206f78b64e7354143578b4b75645d2e1bf1f7fbf29fac074bbfc13901016094f46bd473b22541290bf5f0aa6a52cb3cdac3e

test:
  secret_key_base: 12d430e3f20c6cdc787cd26c2900b404df4935a1b14b5fcad2d5db251ed69365d9df085ab9bff3df4c3da072fd9e4e32ef9f16a8412aeac78f96a7cc82054a41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
